# Diese Datei sagt dem Server, wie dein Plugin heißt und welche Befehle es gibt.
name: MeinServer
version: '${version}'
# Der Pfad zur Haupt-Klasse (Paket + Klassenname)
main: de.meinserver.MeinServerPlugin
description: Mein erster eigener Minecraft-Server (1.8.8)
authors: [DeinName]

# Hier werden alle Befehle (Commands) angemeldet
commands:
  hallo:
    description: Begrüßt den Spieler
    usage: /hallo
  heile:
    description: Heilt dich vollständig
    usage: /heile
